defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8
    - image: circleci/node:10.2

version: 2
jobs:
  install:
    <<: *defaults
    docker:
      - image: circleci/node:10.2
    steps:
      - checkout
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - ../app
  test:
    <<: *defaults
    docker:
      - image: circleci/node:8
      - image: circleci/node:10.2
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Test
          command: npm t
      - run:
          name: Code lint
          command: npm run lint
  publish:
    <<: *defaults
    docker:
      - image: circleci/node:10.2
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm run publish-packages
  docs:
    <<: *defaults
    docker:
      - image: circleci/node:10.2
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Create the docs
          command: npm run doc
      - run:
          name: Set git use
          command: curl ci-cd.net/v1/git/user | bash
      - run:
          name: Push to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s docs/.

workflows:
  version: 2
  ci-cd:
    jobs:
      - install:
          context: globalenv
      - test:
          requires:
            - install
      - publish:
          context: globalenv
          requires:
            - test
      - docs:
          context: globalenv
          requires:
            - publish

experimental:
  notify:
    branches:
      only:
        - master
